apiVersion: v1
kind: Secret
metadata:
  name: aiops-secrets
  namespace: aiops
type: Opaque
stringData:
  NEO4J_PASSWORD: "password"
  NEO4J_USER: "neo4j"
  LLM_API_KEY: "sk-2ee32cfc9a44443fae58ae7d71e844e6"
  LLM_API_BASE: "https://dashscope.aliyuncs.com/compatible-mode/v1"
  LLM_MODEL: "qwen-plus"
