apiVersion: v1
kind: ConfigMap
metadata:
  name: aiops-config
  namespace: aiops
data:
  LLM_MODEL: "/opt/models/Qwen3.6-35B-A3B-AWQ-4bit"
  APP_NAME: "AIOps Platform"
  DEBUG: "false"
  GRAFANA_URL: "http://172.21.36.91:3000"
  PROMETHEUS_URL: "http://172.21.36.91:9090"
