apiVersion: v1
kind: ConfigMap
metadata:
  name: aiops-config
  namespace: aiops
data:
  LLM_MODEL: "qwen-plus"
  APP_NAME: "AIOps Platform"
  DEBUG: "false"
  GRAFANA_URL: "http://47.76.53.232:3000"
  PROMETHEUS_URL: "http://47.76.53.232:9090"
