apiVersion: v1
kind: Service
metadata:
  name: kg-api
  namespace: aiops
spec:
  selector:
    app: kg-api
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: kg-api-nodeport
  namespace: aiops
spec:
  selector:
    app: kg-api
  ports:
  - port: 8001
    targetPort: 8001
    nodePort: 30081
    protocol: TCP
  type: NodePort
