# ⚠️ 此文件由 k8s/scripts/seal-secrets.sh 生成，请勿手工修改！
# 加密数据基于集群 sealed-secrets controller 公钥（172.21.36.94），
# 仅可在该集群解密，提交到 Git 是安全的。
# 注意：本 Secret 包含 2026-08-07 轮换后的新 SSH 私钥，旧私钥已失效。
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aiops-ssh-secret
  namespace: aiops
spec:
  encryptedData:
    id_rsa: AgBPkrnsfIMerCXFQEvprVfeNmoka2KIk/YD8OZoxVHXULcCy1DbMvKRmD5s30R3pyr35qKAAEPLDCN4Zs/PnKpWvRDbNZPFFWXdei2WBYIHoTbZyH9Fb4Fx6Hpn0NfNwma5fQeREQgcOdpylRtAyxTdiqy6tBA6mqglSCbd36QoYBDrFD6Y6CdIflBG0GgUVhLLPYMf+f0WQpE8jvgJEPzKO9xDzucXhhXI/5tasKqvCC+v3liXsWyqhgbo6SM8cEoAn1LCtcZnVmpS5rDRaC/NvlLIcJUGiduD3r45wmL6sOVs0N/44iTCL1wY9bSTo1RbQX+2pMW2iXSoglHfERSpkw+tvtFgeN55Ptf+oBZ47lLv3S32kNXt2fv14XusWJmTybfMFCEpa1XoiRAASkvmxuYKy/uoC/YcmbthuXEl4vXtcw56ZWUDc7guYhrKaVNeYFtlcTRkh+2h5nuqW9JX3GAi0kbzgRYLXcSTC/9SPSjZAQzPPBFE+baJ8CfS1MGxx8X2tgwRyFDDhmNK02wsU+2RBPNyISNNnjXxr028ghDF+yYHuQVZfH7LfCyRlAO44Tb80oQ7PSXGgyGqPeX0ZK7w8uZP3nWIMr/Hf3aZWzYmsU/NNNpYG+qCsqNeaFRAMgiC4WKkVRV+rMbavDh/f+IhQYmfe4Y3PZ1U9ixVU+yyALrEvtbNBGgJvFFWYpIzMJHWyHeCv9A1M/K45hJFdV1o+w0aBQeukyj9tpnPA13wX1LsWorm7lQTyyhxFsKHS6mrWi8iwkNNZoAVmeyPmlDBSGmlSo13EW8naQioJZy85dJ8SWpbcBu9n2YF9FekRqYG1mQcelxW12ydVuBjc42UbC2JAjA6gZM4uKocJ9R+Vgksf7Ak1sffWquBQCjBxVmZR/j9o+OhiVHxjYSbfUeAgZQmarX27oHm3PFVhqmA+Bojs6fYzxXQUx5wXHScJPwR/rVixIhzCDjbBdcogC+1P7s2hmfVK1Wi8GpM9h/CFG2rCZNxM8fic2l1dGYo3DZsGGGtuPoXY0L6pDuA884XR+Ep3+4wa0gAowxgA6uR72Q5xwJ1j71gYe8Xh0MJqHPlGI00/8UYFi6uWyg/Koy5Gdut1Pc9iWJ7Kz+Y35aMYHN7/o9IzjmHcY9NZiyWMpKQWwj4qDQ358z2mZ0Szlw84GLR6+HKXfO6WYAK/eRn3duJkpU8JYYURUPKtMmaUdOGB2uVnG5rH7eYoQne0CLovBph3iF/iRrFTCifJg7X8g==
  template:
    metadata:
      creationTimestamp: null
      name: aiops-ssh-secret
      namespace: aiops
    type: Opaque
